---

- name: Create a directory if it does not exist
  file:
    path: "{{ traefik.config_path | default('/opt/docker_volumes/traefik') }}"
    state: directory
    mode: 0755
  tags:
    - traefik

- name: Render traefik.toml
  template:
    src: "traefik.toml.j2"
    dest: "{{ traefik.config_path | default('/opt/docker_volumes/traefik') }}/traefik.toml"
  notify:
    - restart traefik
  tags:
    - traefik

- name: Create acme.json
  file:
    path: "{{ traefik.config_path | default('/opt/docker_volumes/traefik') }}/acme.json"
    mode: 0600
    state: touch
  tags:
    - traefik

- name: Deploy container
  docker_container:
    name: traefik
    image: traefik:v2.1
    state: started
    restart_policy: always
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ traefik.config_path | default('/opt/docker_volumes/traefik') }}/traefik.toml:/etc/traefik/traefik.toml"
      - "{{ traefik.config_path | default('/opt/docker_volumes/traefik') }}/acme.json:/acme.json"
    networks:
      - name: "{{ traefik.docker.network | default('bridge') }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik-router-redirect.entrypoints: "http"
      traefik.http.routers.traefik-router-redirect.rule: "Host(`{{ traefik.dashboard.domain }}`)"
      traefik.http.routers.traefik-router-redirect.middlewares: "traefik-router-redirectscheme"
      traefik.http.routers.traefik-router.rule: "Host(`{{ traefik.dashboard.domain }}`)"
      traefik.http.routers.traefik-router.tls: "true"
      traefik.http.routers.traefik-router.tls.certresolver: "letsencrypt"
      traefik.http.routers.traefik-router.service: api@internal
      traefik.http.routers.traefik-router.entrypoints: https
      traefik.http.routers.traefik-router.middlewares: "traefik-router-auth"
      traefik.http.middlewares.traefik-router-redirectscheme.redirectscheme.scheme: "https"
      traefik.http.middlewares.traefik-router-auth.basicauth.users: "{{ traefik.dashboard.users }}"
  tags:
    - traefik
