---

- name: Create a directory if it does not exist
  file:
    path: "{{ traefik.config_path | default('/opt/docker_volumes/traefik') }}"
    state: directory
    mode: 0755
  tags:
    - traefik

- name: Render traefik.toml
  template:
    src: "traefik.yaml.j2"
    dest: "{{ traefik.config_path | default('/opt/docker_volumes/traefik') }}/traefik.yaml"
  notify:
    - restart traefik
  tags:
    - traefik

- name: Create acme.json
  file:
    path: "{{ traefik.config_path | default('/opt/docker_volumes/traefik') }}/acme.json"
    mode: 0600
    state: touch
  tags:
    - traefik

- name: Deploy container
  docker_container:
    name: traefik
    image: traefik:v2.2
    state: started
    restart_policy: always
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ traefik.config_path | default('/opt/docker_volumes/traefik') }}/traefik.yaml:/etc/traefik/traefik.yaml"
      - "{{ traefik.config_path | default('/opt/docker_volumes/traefik') }}/acme.json:/acme.json"
    networks: "{{ traefik.docker_container.networks | default(traefik_docker_container_networks_default) }}"
    labels:
      traefik.enable: "true"
  tags:
    - traefik
